# File to test programs for learning as part of INSAID

#### Rahul Tate question

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,9)
matrix_fab = arr.reshape(3,3)

In [17]:
def generate():
    print(np.mean(matrix_fab[1,:]))

In [16]:
generate()

1.0


In [13]:
print(matrix_fab[0,:])

[0 1 2]


In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
matrix_fab

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
abc = matrix_fab - matrix_fab.mean(axis = 1, keepdims=True)
abc

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])